name: pr docs
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: master -> docs
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: rebase
          from_branch: master
          target_branch: docs
          github_token: "${{ secrets.GITHUB_TOKEN }}"
